disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - multiple_closures_with_trailing_closure
  - switch_case_alignment

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - toggle_bool

line_length:
  warning: 120
  error: 160
  
function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - up
    - url
    - dx
    - dy
    - i
    - j
    - k
    - x
    - y
    - z

included:
  - Sources
  - Tests
  - iAppsTask

excluded:
  - Pods
  - .build
  - fastlane
  - R.generated.swift
  - Carthage
  - DerivedData
  - "**/*.generated.swift"
